"Cog: AdvancedUptime":
  - advanceduptime/*
"Cog: AlphaNato":
  - alphanato/*
"Cog: BubbleWrap":
  - bubblewrap/*
"Cog: Codify":
  - codify/*
"Cog: Edition":
  - edition/*
"Cog: Dehoister":
  - dehoister/*
"Cog: NameGenerator":
  - namegenerator/*
"Cog: PingInvoke":
  - pinginvoke/*
"Cog: PingOverride":
  - pingoverride/*
"Cog: RAM":
  - ram/*
"Cog: SendCards":
  - sendcards/*
"Cog: Staff":
  - staff/*
"Cog: TextManipulator":
  - textmanipulator/*
"Cog: TimesTables":
  - timestables/*
"Cog: Vinfo":
  - vinfo/*
"Cog: VoteChannel":
  - votechannel/*
"Category: Meta":
  - .github/*
  - .github/**
"Type: Docs":
  - docs/**/*
  - ./*.rst
